# Generated by Django 5.0.4 on 2024-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tafseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.IntegerField()),
                ('ayah', models.IntegerField()),
                ('text', models.TextField(editable=False)),
            ],
        ),
    ]
